# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Building Bridge Main (68667c24-f266-44a5-ba84-5ded78261dd7)'
    backendAzureRmResourceGroupName: 'BizNet-Development'
    backendAzureRmStorageAccountName: 'biznetdevstorage'
    backendAzureRmContainerName: 'biznet-images'
    backendAzureRmKey: 'terraform/new-unisite.tf'


